/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 can.glb --transform 
Files: can.glb [6.38MB] > C:\Users\janni\Documents\Development\Web\React\Übung\monster\public\can-transformed.glb [207.56KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/can-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Top.geometry} material={materials['Material.001']} position={[-0.009, 0.053, 0.186]} />
    </group>
  )
}

useGLTF.preload('/can-transformed.glb')
